"""Generation: kokoro in, a playable file out.

Written before the implementation and expected to fail by not importing.

These are the three rows with no seam to substitute at, so they run against the
real engine or not at all. `importorskip` skips the module where kokoro is
absent rather than reporting a pass, because a skip that reads as a pass is the
thing this suite is trying not to build.
"""

import wave
from pathlib import Path

import pytest

pytest.importorskip("kokoro", reason="FR-1.1 has no seam; it needs the real engine")

from skid.generation import Generator


# COVERS: FR-1.2 | positive
def test_generation_writes_a_readable_wav(tmp_path: Path) -> None:
    """A file, not a stream, and one the stdlib can open.

    Reading it back with `wave` is also what keeps FR-1.5 true: the module that
    writes it is the standard library's, not an audio library.
    """
    clip = tmp_path / "clip.wav"

    Generator().generate("Hi, silo here.", clip)

    assert clip.exists()
    with wave.open(str(clip), "rb") as handle:
        assert handle.getnframes() > 0
        assert handle.getframerate() > 0


# COVERS: FR-1.1 | positive
def test_generation_uses_kokoro(tmp_path: Path) -> None:
    """Speech is generated by kokoro, and different text gives different audio."""
    first = tmp_path / "first.wav"
    second = tmp_path / "second.wav"
    generator = Generator()

    generator.generate("one", first)
    generator.generate("a considerably longer sentence than the first", second)

    assert second.stat().st_size > first.stat().st_size


# COVERS: FR-5.1 | property
def test_the_model_is_loaded_once_across_submissions(tmp_path: Path) -> None:
    """The backend holds the model warm, so the second clip does not pay start-up.

    Asserted as identity rather than as a duration: the pipeline object a second
    call uses is the one the first call built. A timing assertion here would be
    a flaky test of the machine rather than of skid.
    """
    generator = Generator()

    generator.generate("first", tmp_path / "a.wav")
    loaded = generator.pipeline
    generator.generate("second", tmp_path / "b.wav")

    assert generator.pipeline is loaded


# COVERS: FR-6.5 | negative
def test_an_unknown_voice_is_refused() -> None:
    """A voice kokoro does not have must not reach the record.

    One accepted typo would make every later generation fail, and FR-4.5 has
    already told the caller its submission was accepted, so nobody would learn
    why the machine went quiet.
    """
    with pytest.raises(ValueError):
        Generator(voice="af-heart-with-a-typo")
