"""Generation: kokoro in, a playable file out.

Written before the implementation and expected to fail by not importing.

These are the three rows with no seam to substitute at, so they run against the
real engine or not at all. `importorskip` skips the module where kokoro is
absent rather than reporting a pass, because a skip that reads as a pass is the
thing this suite is trying not to build.
"""

import wave
from pathlib import Path

import pytest

from skid.generation import Generator

pytest.importorskip("kokoro", reason="FR-1.1 has no seam; it needs the real engine")


# COVERS: FR-1.2 | positive
def test_generation_writes_a_readable_wav(tmp_path: Path) -> None:
    """A file, not a stream, and one the stdlib can open.

    Reading it back with `wave` is also what keeps FR-1.5 true: the module that
    writes it is the standard library's, not an audio library.
    """
    clip = tmp_path / "clip.wav"

    Generator().generate("Hi, silo here.", clip)

    assert clip.exists()
    with wave.open(str(clip), "rb") as handle:
        assert handle.getnframes() > 0
        assert handle.getframerate() > 0


# COVERS: FR-1.1 | positive
def test_generation_uses_kokoro(tmp_path: Path) -> None:
    """Speech is generated by kokoro, and different text gives different audio."""
    first = tmp_path / "first.wav"
    second = tmp_path / "second.wav"
    generator = Generator()

    generator.generate("one", first)
    generator.generate("a considerably longer sentence than the first", second)

    assert second.stat().st_size > first.stat().st_size


# COVERS: FR-5.1 | property
def test_the_model_is_loaded_once_across_submissions(tmp_path: Path) -> None:
    """The backend holds the model warm, so the second clip does not pay start-up.

    Asserted as identity rather than as a duration: the pipeline object a second
    call uses is the one the first call built. A timing assertion here would be
    a flaky test of the machine rather than of skid.
    """
    generator = Generator()

    generator.generate("first", tmp_path / "a.wav")
    loaded = generator.pipeline
    generator.generate("second", tmp_path / "b.wav")

    assert generator.pipeline is loaded


# COVERS: FR-10.7 | positive
def test_a_declared_pipeline_overrides_the_one_the_id_implies() -> None:
    """An Italian speaker reading English, which is what was chosen by ear.

    Asserted against the pipeline kokoro actually built rather than against what
    skid stored, because the failure this guards is skid recording a code and
    then handing kokoro the other one.
    """
    assert Generator(voice="if_sara", pipeline="a").pipeline.lang_code == "a"
    assert Generator(voice="if_sara").pipeline_code == "i"


# COVERS: FR-10.7 | property
def test_switching_voices_keeps_one_model_across_pipelines() -> None:
    """Assignment moves between voices constantly, so a switch must stay cheap.

    Two phonemisers, one model. Dropping the pipeline on every change would pay
    model start-up on most submissions, and caching without sharing the model
    would hold a second copy of 1.6 GB.
    """
    generator = Generator(voice="af_bella")
    american = generator.pipeline

    generator.set_voice("bf_alice")
    british = generator.pipeline

    assert american is not british
    assert american.model is british.model
    assert generator.pipeline is british


# COVERS: FR-6.5 | negative
def test_an_unknown_voice_is_refused() -> None:
    """A voice kokoro does not have must not reach the record.

    One accepted typo would make every later generation fail, and FR-4.5 has
    already told the caller its submission was accepted, so nobody would learn
    why the machine went quiet.
    """
    with pytest.raises(ValueError):
        Generator(voice="af-heart-with-a-typo")
