"""Generation: kokoro in, a playable file out.

These are the three rows with no seam to substitute at, so they run against the
real engine or not at all. `importorskip` skips the module where kokoro is
absent rather than reporting a pass, because a skip that reads as a pass is the
thing this suite is trying not to build.
"""

import wave
from pathlib import Path

import numpy as np
import pytest

from skid.generation import Generator

pytest.importorskip("kokoro", reason="FR-1.1 has no seam; it needs the real engine")


# COVERS FR-1.2 | positive
def test_generation_writes_a_readable_wav(tmp_path: Path) -> None:
    """A file, not a stream, and one the stdlib can open.

    Reading it back with `wave` is also what keeps FR-1.5 true: the module that
    writes it is the standard library's, not an audio library.
    """
    clip = tmp_path / "clip.wav"

    Generator().generate("Hi, silo here.", clip)

    assert clip.exists()
    with wave.open(str(clip), "rb") as handle:
        assert handle.getnframes() > 0
        assert handle.getframerate() > 0


# COVERS FR-1.1 | positive
def test_generation_uses_kokoro(tmp_path: Path) -> None:
    """Speech is generated by kokoro, and different text gives different audio."""
    first = tmp_path / "first.wav"
    second = tmp_path / "second.wav"
    generator = Generator()

    generator.generate("one", first)
    generator.generate("a considerably longer sentence than the first", second)

    assert second.stat().st_size > first.stat().st_size


# COVERS FR-5.1 | property
def test_the_model_is_loaded_once_across_submissions(tmp_path: Path) -> None:
    """The backend holds the model warm, so the second clip does not pay start-up.

    Asserted as identity rather than as a duration: the pipeline object a second
    call uses is the one the first call built. A timing assertion here would be
    a flaky test of the machine rather than of skid.
    """
    generator = Generator()

    generator.generate("first", tmp_path / "a.wav")
    loaded = generator.pipeline
    generator.generate("second", tmp_path / "b.wav")

    assert generator.pipeline is loaded


# COVERS FR-10.7 | positive
def test_a_declared_pipeline_overrides_the_one_the_id_implies() -> None:
    """An Italian speaker reading English.

    Asserted against the pipeline kokoro actually built rather than against what
    skid stored, because the failure this guards is skid recording a code and
    then handing kokoro the other one.
    """
    assert Generator(voice="if_sara", pipeline="a").pipeline.lang_code == "a"
    assert Generator(voice="if_sara").pipeline_code == "i"


# COVERS FR-10.7 | property
def test_switching_voices_keeps_one_model_across_pipelines() -> None:
    """Assignment moves between voices constantly, so a switch must stay cheap.

    Two phonemisers, one model. Dropping the pipeline on every change would pay
    model start-up on most submissions, and caching without sharing the model
    would hold a second copy of 1.6 GB.
    """
    generator = Generator(voice="af_bella")
    american = generator.pipeline

    generator.set_voice("bf_alice")
    british = generator.pipeline

    assert american is not british
    assert american.model is british.model
    assert generator.pipeline is british


# COVERS FR-1.10 | positive
def test_the_model_is_v1_1_zh() -> None:
    """Asked of the model kokoro built, not of the constant skid passed it."""
    assert Generator().pipeline.model.repo_id == "hexgrad/Kokoro-82M-v1.1-zh"


# COVERS FR-1.11 | property
def test_each_voice_comes_from_the_release_that_publishes_it() -> None:
    """The path kokoro is handed sits in the right repository's cache.

    A pack from the model's own repository would be the v1.1-zh one for every
    voice, and `af_heart` is not published there.
    """
    generator = Generator()

    old = Path(generator.pack_for("af_heart")).parts
    new = Path(generator.pack_for("af_maple")).parts

    assert "models--hexgrad--Kokoro-82M" in old
    assert "models--hexgrad--Kokoro-82M-v1.1-zh" in new


# COVERS FR-1.11 | positive
def test_an_old_voice_and_a_new_one_both_render(tmp_path: Path) -> None:
    """The shortlist's voices and the three new ones speak on one model."""
    generator = Generator(voice="af_heart")
    generator.generate("one", tmp_path / "old.wav")

    generator.set_voice("bf_vale")
    generator.generate("one", tmp_path / "new.wav")

    for name in ["old.wav", "new.wav"]:
        with wave.open(str(tmp_path / name), "rb") as handle:
            assert handle.getnframes() > 0


def _gain_applied(voice: str, tmp_path: Path) -> float:
    """How much louder skid's file is than kokoro's own output for `voice`.

    The same text through the same warm pipeline and pack, so the only
    difference between the two is what skid did on the way to the file.
    """
    generator = Generator(voice=voice)
    clip = generator.generate("The gate is green.", tmp_path / f"{voice}.wav")
    with wave.open(str(clip), "rb") as handle:
        written = np.frombuffer(handle.readframes(handle.getnframes()), dtype="<i2")
    chunks = generator.pipeline("The gate is green.", voice=generator.pack_for(voice))
    raw = np.concatenate([chunk.audio.numpy() for chunk in chunks]) * 32767
    return float(
        np.sqrt(np.mean(written.astype(float) ** 2)) / np.sqrt(np.mean(raw**2))
    )


# COVERS FR-1.12 | positive
def test_bf_vale_is_raised_by_a_quarter(tmp_path: Path) -> None:
    """The measured correction, applied to the samples skid writes."""
    assert _gain_applied("bf_vale", tmp_path) == pytest.approx(1.25, rel=0.01)


# COVERS FR-1.12 | negative
def test_no_other_voice_is_changed(tmp_path: Path) -> None:
    """af_sol is the loudest voice measured, and it is left as kokoro made it."""
    assert _gain_applied("af_sol", tmp_path) == pytest.approx(1.0, rel=0.01)


# COVERS FR-6.5 | negative
def test_an_unknown_voice_is_refused() -> None:
    """A voice kokoro does not have must not reach the record.

    One accepted typo would make every later generation fail, and FR-4.5 has
    already told the caller its submission was accepted, so nobody would learn
    why the machine went quiet.
    """
    with pytest.raises(ValueError):
        Generator(voice="af-heart-with-a-typo")
